version: '3'

services:
  db:
    image: 'postgres:16-alpine'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=MC426
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d MC426"]
      interval: 5s
      timeout: 5s
      retries: 5
  flask-app:
    build: ./
    entrypoint: ["bash", "./entrypoint.sh"]
    environment:
      - POSTGRES_DB=MC426
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - .:/MC426
    ports:
      - 5005:5000
    depends_on:
      db:
        condition: service_healthy
      test:
        condition: service_completed_successfully
  test:
    build: ./
    command: python3 -m unittest tests/test_database.py tests/test_app.py tests/test_utils.py
    environment:
      - POSTGRES_DB=MC426
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
